### ISSUE TITLE
CGG 2015 Voting Transactional Email Templates

### ISSUE THREAD

**Issue by ArielSD** [DoSomething/voting-app#436]
We'll need to trigger a transactional email for users who vote for Celebs Gone Good after registering with their email address. 
We already have this template (https://us4.admin.mailchimp.com/templates/edit?id=56617) from AGG 2015; Could we update the copy and banner in the template and then rename it? That way, we could just use the existing voting app configuration, and point to the same template with the new name.

Here are the four voting confirmation templates for CGG 2015 with new nomenclature:

CGG2015-voting-confirmation-US: https://us4.admin.mailchimp.com/templates/editor?id=56617
CGG2015-voting-confirmation-GL: https://us4.admin.mailchimp.com/templates/editor?id=56761
CGG2015-voting-confirmation-MX: https://us4.admin.mailchimp.com/templates/editor?id=56765
CGG2015-voting-confirmation-BR: https://us4.admin.mailchimp.com/templates/editor?id=56769

**Comment by ArielSD** [comment]
@marahml CCing you on this!

**Comment by deezone** [comment]
@ArielSD Go ahead and make the copy with the new template name. Post the new name in this issue.

**Comment by ArielSD** [comment]
@DeeZone I kept the same template and renames it "CGG2015 Voting Confirmation". We'll just update the copy and banner, does that work?

**Comment by deezone** [comment]
Sounds good.
- I've sent the template to Mandrill to give Message Broker something to work with. Feel free to update as you see fit.
- Will there be a global addition or is there only one template for everyone?
- Change the issue back to me when you're part is done.

**Comment by ArielSD** [comment]
@DeeZone 
Great, thank you! We just have to update copy and the banner. 

If we're able to place incoming users into different lists and MailChimp accounts, then we just need 1 template for everyone. Do we have that capability?

**Comment by deezone** [comment]
@ArielSD Perfect, thanks!

**Comment by deezone** [comment]
@marahml FYI, please see the description for this issue. @ArielSD has created four templates for the CGG first vote transactional email, one each for US, MX, BR and Global. 

I understand that all messages will be English. Due to technical functionality implemented to support multilingual email requests from the Drupal app, requests from the Voting App will need to follow the same format. Requests include `user_country` which defines which template is used.

Initially all four template content will be the same. The separate templates allow for customisation specific to each target user group (US, MX, BR and Global). The customisation functionality is available but not necessary used.

**Comment by DFurnes** [comment]
I think this can be closed since CGG has been launched for a while now. :closed_book:
