### ISSUE TITLE
Birthdate format not adjusting to user location

### ISSUE THREAD

**Issue by deezone** [DoSomething/voting-app#461]
Non-US located users should be presented with a birthdate registration field that expects input in dd/mm/yyyy rather than the US mm/dd/yyyy standard. This is based on the functionality currently on the Drupal user registration form.

![image](https://cloud.githubusercontent.com/assets/2119264/11329501/d5139c88-916a-11e5-986c-d96ea2383e5a.png)

**Comment by DFurnes** [comment]
This was never built for the voting app, but seems like reasonable functionality to add.

**Comment by DFurnes** [comment]
So for some context/discussion, we use PHP's [`strtotime`](http://php.net/manual/en/function.strtotime.php) to [parse dates provided from this form](https://github.com/DoSomething/voting-app/blob/9118e184e03de1f1adf70d1b36412e29d442afcf/app/Models/User.php#L46-L54). The cool thing is that it will try to automatically handle parsing all sorts of dates for us. So a user could enter `10/25/90`, `10/25/1990`, `October 25th 1990` and they'd all refer to the same date.

Unfortunately, it differentiates between `MM/DD/YYYY` and `DD-MM-YYYY` by the separator used in the date:

> Dates in the m/d/y or d-m-y formats are disambiguated by looking at the separator between the various components: if the separator is a slash (/), then the American m/d/y is assumed; whereas if the separator is a dash (-) or a dot (.), then the European d-m-y format is assumed. If, however, the year is given in a two digit format and the separator is a dash (-, the date string is parsed as y-m-d.
> 
> <small>– http://php.net/manual/en/function.strtotime.php</small>

~~It looks like the best solution is for us to associate date formats with country codes (like we do in the Drupal world), and then explicitly parse those formats via [`DateTime::createFromFormat`](http://php.net/manual/en/datetime.createfromformat.php) (and display a relevant placeholder). We lose some of the "magic" but will get more predictable results.~~ I'm tempted to take the hacky solution and just manually switch separators based on locale. Open to arguments otherwise if anyone thinks this isn't a good idea though!
