### ISSUE TITLE
Pull MX and BZ mobile numbers from CGG 2014 and AGG 2015

### ISSUE THREAD

**Issue by classicfreddie** [DoSomething/voting-app#488]
@angaither We want to pull past Mexican and Brazilian numbers we collected from past iterations of Celebs Gone Good and Athletes Gone Good and import them into mGage. 

@DeeZone Ideally I'd like to import them into mGage and also send them a message. Not sure if it can happen at once, or if we need to first complete the import and then set up a broadcast. I can create new lists to put these users into. 

**Related**:
- Message Broker Trello card: https://trello.com/c/2rAW0nqk

**Comment by deezone** [comment]
@angaither Perhaps if you can generate the CSV file I'll take care of the import?

@classicfreddie Not sure if a new list makes sense. What do you think of using the existing MX and BR list and using the "smart list" feature to create sublists? We could assign a "property" to the imported numbers and use a smart list to filter out the current CGG numbers.

In addition, perhaps we should remove the "_CelebsGoneGood_2015" from the list names rather than the event specific "Brazil_CelebsGoneGood_2015"?

We could run this past Kelly? My quick read of the Smart List section seems to make sense.

**Comment by angaither** [comment]
@classicfreddie @DeeZone drop CSVs of data from CGG 2014 & AGG in slack

**Comment by classicfreddie** [comment]
@DeeZone ok to close this ?

**Comment by deezone** [comment]
- Brazil_CelebsGoneGood_2015: 429
- Mexico_CelebsGoneGood_2015: 82

Looks like it's working...

And the import is done:

Brazil_CelebsGoneGood_2014: 6
Mexico_CelebsGoneGood_2014: 57
