### ISSUE TITLE
Add optional sponsor logo

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/voting-app#504]
Mocks TBD.

**Comment by DFurnes** [comment]
And mocks, via Keri! :clap: 

![screen shot 2016-04-07 at 11 08 44 am](https://cloud.githubusercontent.com/assets/583202/14356023/289fed6e-fcb1-11e5-8ef7-02210f802efb.png)

**Comment by katiecrane** [comment]
![289fed6e-fcb1-11e5-8ef7-02210f802efb](https://cloud.githubusercontent.com/assets/4240292/14356297/4842372a-fcb2-11e5-9121-eac4b24196b0.png)
@DFurnes is this whole part the sponsor logo image? (please say yes)

**Comment by DFurnes** [comment]
I think the "Powered By" part should be text. :grimacing: You should be able to base it off the styles for the [`.center`](http://forge.dosomething.org/#figure) Figure modifier in Forge, but with the "media" part to the right, rather than to the left.

**Comment by namimody** [comment]
@katiecrane I think this might be acting up?

SVG file is uploaded here (I know, sorry :see_no_evil:): http://www.catsgonegood.com/images/settings/sponsor_logo_svg.svg

But the POWERED BY text is appearing indented and the transparency of the white on black image is causing it not to show up. The indentation seems to for sure be a bug based on the current header, but perhaps the svg file is just poorly converted, which is why the white is transparent?
![image](https://cloud.githubusercontent.com/assets/12396076/14541265/1187b822-0257-11e6-9ae2-878ccc18793c.png)

**Comment by katiecrane** [comment]
@namimody The image is actually transparent in the middle so it's showing up just fine 😁 well maybe not fine, but it's because of how the image is I think. Can you put a different one in there so you can see what it could look like?
